### ISSUE TITLE
location of git repo for base-environment image is wrong (or the repo is private)

### ISSUE THREAD

**Issue by paulczar** [eduk8s/eduk8s-docs#11]
In the docs ( https://github.com/eduk8s/eduk8s-docs/blob/15fe7e86c1b2790cdb32a20e7e87b6904093276a/docs/workshop-content/building-an-image.rst#bases-images-and-version-tags ) it mentions [https://github.com/eduk8s/base-environment/releases](https://github.com/eduk8s/base-environment/releases) as the location to find the base-environment ... However I get a 404 error there.

I was looking to find it to create a `PR` to include the `tree` linux command without having to pop in and out of root in downstream images or try and add it as a binary under `/opt/eduk8s/bin`

**Comment by GrahamDumpleton** [comment]
Have added the ``tree`` program to ``base-environment`` image.

If need to know the image versions because creating a derived custom workshop image, can find versions for now at:

* https://quay.io/repository/eduk8s/base-environment?tab=tags

As repos currently private, going to update links to refer to quay.io for tags.

**Comment by GrahamDumpleton** [comment]
Links in docs updated for how to get version tags.
